# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'demo' do
	pod 'CocoaAsyncSocket'
	pod 'CocoaLumberjack'
    pod 'KSYMediaPlayer_iOS'
    pod 'ksyhttpcache'
end

